// Display resources. Keys are stable; values preserve the current interface.
var ST_TEXT_RESOURCES = {
  "autosave.invalid": "Complete the required fields and correct invalid JSON before this change can be saved.",
  "autosave.saved": "Saved",
  "autosave.pending": "Changes pending",
  "autosave.saving": "Saving…",
  "autosave.error": "Not saved",
  "autosave.retry": "Retry",
  "autosave.conflict_title": "A newer case version exists",
  "autosave.conflict_message": "Your changes have not overwritten the newer version. Download your draft before loading the version from Drive, then review the differences.",
  "autosave.export_reload": "Download draft and reload",
  "dialog.notice": "Notice",
  "dialog.ok": "OK",
  "dialog.delete": "Delete",
  "dialog.done": "Done",
  "dialog.delete_case": "Delete case",
  "dialog.delete_equipment": "Delete equipment",
  "dialog.delete_equipment_message": "Remove this equipment from the current simulation? Its results will be cleared.",
  "simulation.rename": "Rename simulation",
  "simulation.name": "Simulation name",
  "simulation.delete": "Delete simulation",
  "simulation.delete_message": "Delete this simulation and its results? ",
  "simulation.keep_one": "Keep at least one simulation in the case. You can delete the entire case in Settings.",
  "simulation.copy_name": "Copy of ",
  "simulation.new_equipment": "New equipment",
  "editor.json_note": "Advanced engine configuration. These values are populated by the forms and Sheet import. Most users do not need to edit JSON. Invalid JSON is not saved; correct it to resume automatic saving. Conveyor geometry controls take precedence over the corresponding JSON fields.",
  "settings.close_case_storage": "Close the current case before changing its storage folder.",
  "settings.complete_fields": "Complete the required settings before they can be saved.",
  "settings.delete_case_note": "Move the open case and all its simulations to the Drive trash.",
  "scenario.zero": "Zero CAPEX",
  "scenario.medium": "Medium CAPEX / OPEX",
  "scenario.high": "High CAPEX",
  "scenario.static": "Static inputs only",
  "scenario.dynamic": "Dynamic run evidence",
  "scenario.hybrid": "Static + dynamic evidence",
  "scenario.speed_balance": "Match downstream infeed demand",
  "scenario.sensor_debounce": "Tune sensor confirmation delays",
  "scenario.buffer_recovery": "Restore physical accumulation and recovery",
  "scenario.reliability": "Maintenance sensitivity scenario",
  "scenario.no_proposal": "No supported proposal",
  "scenario.insufficient": "Current evidence does not support an automatic change in this category.",
  "scenario.invalid_physics": "Complete the physical line inputs before applying this scenario.",
  "scenario.regression": "This change would invalidate a design check. Resolve the related geometry constraints first.",
  "scenario.create": "Create scenario",
  "scenario.confirm": "Create a separate simulation with the listed changes? The baseline and random seed are preserved. Run the new scenario to measure its effect.",
  "scenario.created": "Scenario created and saved. Review the inputs and run it to evaluate the impact.",
  "scenario.stale": "The source simulation changed. Generate a new proposal before applying it.",
  "scenario.evidence": "Evidence",
  "scenario.design_checks": "Design checks and missing inputs",
  "scenario.basis_note": "These checks implement the supplied design brief where inputs exist; they do not certify handbook compliance. CAPEX levels describe intervention scale, not a cost estimate or financial return. Buffer coverage uses the adjacent upstream machine's MTTR for microstops up to 4 minutes. Unmodeled turn losses, filled-container diameter and PLC desired-state behavior are not assumed.",
  "scenario.maintenance_note": "Explicit maintenance hypothesis: MTBF +20%, MTTR −15%. This is a sensitivity test, not a guaranteed improvement or a consequence of conveyor tuning. Maintenance spending may be OPEX.",
  "scenario.unverified": "Expected direction is a hypothesis. Numerical OEE, throughput and loss improvements require a new run and comparison.",
  "scenario.turn_diameter": "90° turns and filled-container diameter",
  "scenario.desired_state": "Pacemaker desired state and V-graph",
  "scenario.coverage": "Accumulation coverage (1–2× MTTR)",
  "scenario.major_failure": "Major failures outside the microstop buffer target",
  "scenario.not_evaluated": "Not evaluated: required inputs or model support are missing",
  "scenario.review": "Engineering review",
  "scenario.pulse": "Normal sensor pulse (s)",
  "scenario.gap": "Normal sensor clear gap (s)",
  "scenario.recovery": "Recovery length (mm)",
  "scenario.overflow": "Required overflow length (mm)",
  "scenario.added_length": "Added length (mm)",
  "scenario.failure": "Observed failure time (s)",
  "scenario.availability": "Intrinsic availability (%)",
  "scenario.speed": "Recommended infeed speed (mm/s)",
  "scenario.overflow_units": "Observed overflow (units)",
  "scenario.mtbf_factor": "MTBF multiplier",
  "scenario.mttr_factor": "MTTR multiplier",
  "assistant.compact_context": "Compact context:",
  "assistant.equipment_included": " equipment included. Replay samples, event logs and raw Sheet rows excluded.",
  "assistant.history_omitted": " Older messages omitted: ",
  "assistant.rejected_proposals": "Some proposed changes did not pass the model checks and cannot be applied. Request a revised proposal.",
  "assistant.answer_shortened": "Answer shortened for conversation storage.",
  "auth.restoring": "Connecting to your workspace…",
  "client.verifying_your_google_access": "Verifying your Google access…",
  "client.saving_your_changes": "Saving your changes…",
  "client.discard_unsaved_changes_and_return_to_cases": "Discard unsaved changes and return to cases?",
  "client.signed_out_of_line_studio_your_google_account_remains_signed_in": "Signed out of Line Studio. Your Google account remains signed in.",
  "client.loading_console": "Loading console…",
  "client.open_settings_to_connect_a_drive_folder_before_creating_a_case": "Open Settings to connect a Drive folder before creating a case.",
  "client.settings_could_not_be_saved": "Settings could not be saved.",
  "client.settings_saved": "Settings saved",
  "client.move_case": "Move Case \"",
  "client.to_the_drive_trash": "\" to the Drive trash?",
  "client.case_moved_to_drive_trash": "Case moved to Drive trash.",
  "client.discard_unsaved_changes_and_open_this_case": "Discard unsaved changes and open this case?",
  "client.case_loaded": "Case loaded.",
  "client.active_simulation": "Active simulation: ",
  "client.this_is_a_clone_the_source_remains_unchanged": ". This is a clone; the source remains unchanged.",
  "client.case_saved_as_revision": "Case saved as revision ",
  "client.applied_sheet_selection_to": "Applied Sheet selection to ",
  "client.added": " added, ",
  "client.updated_save_the_case": " updated. Saving automatically.",
  "client.run_again_to_refresh_results": " Run again to refresh results.",
  "client.unsaved_changes": " · unsaved changes",
  "client.what_if": " · What-If: ",
  "client.id": "ID: ",
  "client.active": " · Active: ",
  "client.revision": " · Revision ",
  "client.imported_from": "Imported from ",
  "client.mtbf_drives_random_failure_intervals_mttr_is_a_fixed_repair_duration_review": ". MTBF drives random failure intervals; MTTR is a fixed repair duration. Review the stored import assumptions before running.",
  "client.step": "Step ",
  "client.bpm": " BPM",
  "client.delete_equipment": "Delete equipment",
  "client.edit_equipment": "Edit equipment",
  "client.collapse_details": "Collapse details",
  "client.total_installed_conveyor_length_measured_from_the_upstream_discharge_toward": "Total installed conveyor length, measured from the upstream discharge toward the downstream infeed.",
  "client.reserved_downstream_length_between_the_prime_photocell_and_the_downstream_m": "Reserved downstream length between the Prime photocell and the downstream machine infeed.",
  "client.physical_package_length_in_the_direction_of_travel_it_determines_the_photoe": "Physical package length in the direction of travel. It determines the photoeye occupied time.",
  "client.centre_to_centre_distance_between_packages_leaving_the_upstream_machine": "Centre-to-centre distance between packages leaving the upstream machine.",
  "client.belt_speed_increase_relative_to_upstream_package_discharge_velocity_it_chan": "Belt-speed increase relative to upstream package discharge velocity. It changes package spacing and population.",
  "client.installed_back_up_photocell_position_measured_from_the_upstream_discharge_a": "Installed Back-up photocell position, measured from the upstream discharge. A sustained blocked signal requests the upstream stop.",
  "client.length_that_must_be_cleared_after_the_upstream_discharge_before_a_stop_full": "Length that must be cleared after the upstream discharge before a stop fully takes effect.",
  "client.additional_reject_runout_length_that_must_be_cleared_during_an_upstream_sto": "Additional reject/runout length that must be cleared during an upstream stop.",
  "client.continuous_back_up_blocked_time_required_before_the_simulator_requests_the_": "Continuous Back-up blocked time required before the simulator requests the upstream stop. Normal package pulses do not count.",
  "client.continuous_back_up_clear_time_required_before_the_simulator_releases_the_up": "Continuous Back-up clear time required before the simulator releases the upstream stop. Normal product gaps reset this timer.",
  "client.extra_package_margin_reserved_in_the_required_overflow_calculation_it_is_a_": "Extra package margin reserved in the required overflow calculation. It is a design margin, not randomly created material.",
  "client.delay_from_the_upstream_stop_request_until_its_discharge_response_is_comple": "Delay from the upstream stop request until its discharge response is complete.",
  "client.packages_that_can_still_leave_the_upstream_machine_after_the_stop_request": "Packages that can still leave the upstream machine after the stop request.",
  "client.time_for_the_downstream_machine_to_ramp_after_prime_authorizes_its_start": "Time for the downstream machine to ramp after Prime authorizes its start.",
  "client.back_up_blocked_delay_s": "Back-up blocked delay (s)",
  "client.back_up_clear_delay_s": "Back-up clear delay (s)",
  "client.flowpilot_preview_becomes_available_when_this_conveyor_sits_between_an_upst": "FlowPilot preview becomes available when this conveyor sits between an upstream and downstream machine.",
  "client.required_l_act_l_p_package_length_upstream_discharge_pitch_upstream_bpm_and": "Required: L_act, L_p, package length, upstream discharge pitch, upstream BPM, and conveyor speed factor.",
  "client.calculated": "Calculated: ",
  "client.mm_s": " mm/s · ",
  "client.mm_pitch": " mm pitch · ",
  "client.units_prime": " units · Prime ",
  "client.mm_required_back_up": " mm · required Back-up ≥ ",
  "client.mm_l_rec": " mm · L_rec ",
  "client.mm_normal_photoeye_pulse": " mm · normal photoeye pulse ",
  "client.normal_clear_gap": " · normal clear gap ",
  "client.noise_profile": "Noise profile",
  "client.process_format_data": "Process format data",
  "client.for_equipment_step": " for equipment step ",
  "client.must_contain_a_json_object": " must contain a JSON object.",
  "client.revision_2": " · revision ",
  "client.scenario_edits_not_yet_saved_to_drive": " · scenario edits not yet saved to Drive",
  "client.workspace_tab_active": " workspace-tab-active",
  "client.open_simulation": "Open simulation: ",
  "client.compare_simulations": "Compare simulations",
  "client.compare_two_saved_simulations_from_this_case": "Compare two saved simulations from this Case.",
  "client.simulation_a": "Simulation A",
  "client.input_required": "INPUT REQUIRED",
  "client.evidence": "Evidence: ",
  "client.create_recommended_simulation_b": "Create recommended Simulation B",
  "client.create_a_saved_clone_apply_only_these_inputs_then_review_and_run_the_succes": "Create a saved clone, apply only these inputs, then review and run the successor simulation.",
  "client.no_automatic_clone_is_created_until_the_required_physical_inputs_are_comple": "No automatic clone is created until the required physical inputs are complete.",
  "client.no_priority_change": "NO PRIORITY CHANGE",
  "client.no_material_design_issue_was_detected_in_this_run": "No material design issue was detected in this run",
  "client.the_available_geometry_audit_and_observed_loss_counters_do_not_justify_an_a": "The available geometry audit and observed loss counters do not justify an automatic intervention. Use Clone Simulation only when you have a specific engineering hypothesis to test.",
  "client.evidence_considered": "Evidence considered (",
  "client.global_oee": "Global OEE: ",
  "client.using": "% using ",
  "client.line_losses_starvation": "Line losses: starvation ",
  "client.waiting_for_prime": " · waiting for Prime ",
  "client.failures": " · failures ",
  "client.complete_physical_conveyor_data": "Complete physical conveyor data",
  "client.no_physical_conveyor_can_be_evaluated": "No physical conveyor can be evaluated",
  "client.this_simulation_has_no_conveyor_with_flowpilot_geometry_available_for_a_phy": "This simulation has no conveyor with FlowPilot geometry available for a physical recommendation.",
  "client.add_a_machine_conveyor_machine_section_with_geometry_before_creating_an_aut": "Add a machine → conveyor → machine section with geometry before creating an automatic successor simulation.",
  "client.no_conveyor_metrics_were_saved_with_this_run": "No conveyor metrics were saved with this run.",
  "client.the_physical_audit_is_incomplete_on": "The physical audit is incomplete on ",
  "client.a_safe_sensor_speed_or_buffer_change_cannot_be_calculated_until_the_missing": "A safe sensor, speed, or buffer change cannot be calculated until the missing geometric inputs are supplied.",
  "client.complete_the_listed_flowpilot_fields_save_the_simulation_and_run_it_again_b": "Complete the listed FlowPilot fields, save the simulation, and run it again before creating Simulation B.",
  "client.audit_status": "Audit status: ",
  "client.restore_buffer_recovery": "Restore buffer recovery",
  "client.high_capex": "HIGH CAPEX",
  "client.physical_recovery_margin_is_insufficient_on": "Physical recovery margin is insufficient on ",
  "client.the_conveyor_audit_indicates_that_a_normal_stop_restart_may_consume_the_ava": "The conveyor audit indicates that a normal stop/restart may consume the available accumulation margin before the upstream flow is recovered.",
  "client.set_back_up_to_the_calculated_required_l_bu_of": "Set Back-up to the calculated required L_bu of ",
  "client.mm_and_set_l_act_to_the_minimum_modeled_length_of": " mm and set L_act to the minimum modeled length of ",
  "client.mm": " mm (",
  "client.mm_added": " mm added).",
  "client.the_audit_found_a_geometry_issue_but_the_available_inputs_cannot_derive_a_v": "The audit found a geometry issue, but the available inputs cannot derive a valid recovery length.",
  "client.target": "Target: ",
  "client.audit": " · audit ",
  "client.l_rec": " · L_rec ",
  "client.mm_2": " mm",
  "client.required_l_bu": " · required L_bu ",
  "client.observed_waiting_starvation_is_elevated": " · observed waiting/starvation is elevated",
  "client.tune_back_up_confirmation_timers": "Tune Back-up confirmation timers",
  "client.zero_capex": "ZERO CAPEX",
  "client.normal_photoeye_pulses_can_be_mistaken_for_a_sustained_back_up_signal": "Normal photoeye pulses can be mistaken for a sustained Back-up signal",
  "client.at_least_one_configured_back_up_confirmation_delay_is_not_longer_than_the_m": "At least one configured Back-up confirmation delay is not longer than the modeled occupied pulse or clear gap. The PLC may chatter or stop on normal package spacing.",
  "client.set_blocked_delay_to": "Set blocked delay to ",
  "client.s_and_clear_delay_to": " s and clear delay to ",
  "client.s_these_are_simulated_plc_confirmation_settings_confirm_them_with_controls_": " s. These are simulated PLC confirmation settings; confirm them with controls engineering before plant use.",
  "client.package_pulse_and_gap_timing_are_required_to_derive_a_safe_confirmation_del": "Package pulse and gap timing are required to derive a safe confirmation-delay candidate.",
  "client.normal_occupied_pulse": " · normal occupied pulse ",
  "client.installed_delays": " · installed delays ",
  "client.balance_downstream_infeed_speed": "Balance downstream infeed speed",
  "client.infeed_conveyor_speed_does_not_match_the_calculated_downstream_demand": "Infeed conveyor speed does not match the calculated downstream demand",
  "client.the_current_belt_factor_differs_from_the_flowpilot_infeed_calculation_which": "The current belt factor differs from the FlowPilot infeed calculation, which includes the modeled downstream speed, infeed pitch, and 5% infeed overspeed.",
  "client.change_conveyor_speed_factor_from": "Change conveyor speed factor from ",
  "client.to_the_calculated": "% to the calculated ",
  "client.the_current_factor_is_already_aligned_with_the_calculated_downstream_infeed": "The current factor is already aligned with the calculated downstream infeed demand.",
  "client.recommended_infeed_speed": " · recommended infeed speed ",
  "client.mm_s_2": " mm/s",
  "client.reliability_sensitivity_check": "Reliability sensitivity check",
  "client.low_capex_opex": "LOW CAPEX / OPEX",
  "client.intrinsic_equipment_downtime_is_reducing_the_result": "Intrinsic equipment downtime is reducing the result",
  "client.failures_or_low_intrinsic_availability_were_observed_this_scenario_is_a_tra": "Failures or low intrinsic availability were observed. This scenario is a transparent sensitivity check, not a claim that maintenance will achieve the result.",
  "client.for": "For ",
  "client.critical_machines_test_the_stated_maintenance_assumption_mtbf_1_20_and_mttr": " critical machines, test the stated maintenance assumption: MTBF × 1.20 and MTTR × 0.85.",
  "client.mtbf_and_mttr_are_required_on_at_least_one_non_conveyor_machine": "MTBF and MTTR are required on at least one non-conveyor machine.",
  "client.failure": "Failure ",
  "client.availability_trigger": " · availability trigger ",
  "client.installed_length_l_act": "Installed length L_act",
  "client.prime_reserve_l_p": "Prime reserve L_p",
  "client.created": "Created ",
  "client.from": " from ",
  "client.is_applied_review_the_changed_inputs_and_run_it_when_ready": " is applied; review the changed inputs and run it when ready.",
  "client.simulation_completed_at_its_virtual_safety_ceiling_playback_is_starting": "Simulation completed at its virtual safety ceiling. Playback is starting.",
  "client.simulation_completed_playback_is_starting": "Simulation completed. Playback is starting.",
  "client.duration_sample_interval_and_integer_seed_are_required": "Duration, sample interval, and integer seed are required.",
  "client.reset": "Reset",
  "client.s_frame": " s · frame ",
  "client.time_losses": "Time losses",
  "client.run_resume": "Run / resume",
  "client.pause": "Pause",
  "client.planned_stop": "Planned stop",
  "client.emergency_stop": "Emergency stop",
  "client.reset_run": "Reset + run",
  "client.show_losses": " show-losses",
  "client.critical_pacemaker": "Critical · pacemaker",
  "client.critical_equipment": "Critical equipment",
  "client.mtbf": "MTBF ",
  "client.min_mttr": " min · MTTR ",
  "client.min": " min",
  "client.command": "Command: ",
  "client.nominal": "Nominal ",
  "client.max": " · Max ",
  "client.min_2": " / min",
  "client.accumulation_zone": "Accumulation zone",
  "client.physical_accumulation": " · physical accumulation",
  "client.units_waiting": " units · Waiting ",
  "client.product_already_at_the_downstream_end_of_the_conveyor_and_available_to_the_": "Product already at the downstream end of the conveyor and available to the next machine. Inventory equals In transit plus Waiting.",
  "client.sensor_timing": "Sensor timing",
  "client.normal_photoeye_occupied_time_and_clear_gap_derived_from_product_length_pit": "Normal photoeye occupied time and clear gap derived from product length, pitch, and belt speed.",
  "client.normal_sensor_pulse": "Normal sensor pulse",
  "client.time_one_package_normally_blocks_a_photoeye_at_the_calculated_belt_speed": "Time one package normally blocks a photoeye at the calculated belt speed.",
  "client.normal_clear_gap_2": "Normal clear gap",
  "client.time_the_normal_gap_between_packages_leaves_a_photoeye_clear": "Time the normal gap between packages leaves a photoeye clear.",
  "client.insurance_margin": "Insurance margin",
  "client.extra_package_margin_included_in_the_required_overflow_calculation_it_is_no": "Extra package margin included in the required overflow calculation; it is not material generated during the run.",
  "client.all_material_on_this_physical_conveyor_in_transit_plus_waiting": "All material on this physical conveyor: In transit plus Waiting.",
  "client.product_moving_between_the_upstream_discharge_and_the_downstream_end_of_the": "Product moving between the upstream discharge and the downstream end of the conveyor.",
  "client.prime_photocell_signal_a_product_pass_authorizes_the_downstream_start_a_blo": "Prime photocell signal. A product pass authorizes the downstream start; a blocked state means a queue has reached the sensor.",
  "client.back_up_photocell_signal_only_a_continuously_blocked_signal_starts_the_stop": "Back-up photocell signal. Only a continuously blocked signal starts the stop timer; normal product pulses do not request a stop.",
  "client.installed_usable_length_and_effective_product_pitch_used_to_calculate_physi": "Installed usable length and effective product pitch used to calculate physical capacity.",
  "client.nominal_time_for_material_to_travel_through_the_physical_conveyor": "Nominal time for material to travel through the physical conveyor.",
  "client.material_that_could_not_enter_a_full_physical_zone": "Material that could not enter a full physical zone.",
  "client.required_overflow_length_including_runout_residual_discharge_blocked_delay_": "Required overflow length, including runout, residual discharge, blocked-delay output, and insurance margin.",
  "client.usable_accumulation_length_after_reserving_prime_and_required_overflow_spac": "Usable accumulation length after reserving Prime and required overflow space.",
  "client.calculated_recovery_margin_after_back_up_clears_positive_values_indicate_a_": "Calculated recovery margin after Back-up clears. Positive values indicate a smoother modeled restart.",
  "client.time_the_useful_accumulation_can_continue_feeding_the_downstream_critical_m": "Time the useful accumulation can continue feeding the downstream critical machine.",
  "client.time_the_useful_accumulation_can_accept_upstream_output_before_the_upstream": "Time the useful accumulation can accept upstream output before the upstream machine must be stopped.",
  "client.minimum_downstream_infeed_conveyor_speed_with_the_worksheet_5_overspeed_mar": "Minimum downstream infeed conveyor speed with the worksheet 5% overspeed margin.",
  "client.mm_3": " mm / ",
  "client.not_available": "Not available",
  "client.capacity_floor_length_pitch": " · Capacity: floor(length / pitch) = ",
  "client.units_controls_upstream": " units · Controls upstream: ",
  "client.starts_downstream": " · Starts downstream: ",
  "client.not_configured": "Not configured",
  "client.pulsing_product_passing": "PULSING · product passing",
  "client.blocked_queue_present": "BLOCKED · queue present",
  "client.clear_start_sent": "CLEAR · start sent",
  "client.clear_waiting": "CLEAR · waiting",
  "client.pulsing_normal_flow": "PULSING · normal flow",
  "client.blocked_control_active": "BLOCKED · control active",
  "client.blocked": "BLOCKED ",
  "client.clear": "CLEAR ",
  "client.clear_awaiting_delay": "CLEAR · awaiting delay",
  "client.flowpilot_physical_conveyor_zone": "FlowPilot physical conveyor zone",
  "client.direct_physical_conveyor_zone": "Direct physical conveyor zone",
  "client.physical_zone": "Physical zone",
  "client.units": " units",
  "client.pitch": "Pitch: ",
  "client.speed": "Speed: ",
  "client.reset_playback_to_an_earlier_virtual_time_before_applying_a_scenario_contro": "Reset playback to an earlier virtual time before applying a scenario control.",
  "client.apply_at_the_displayed_virtual_second_and_recalculate_this_simulation_scena": "Apply at the displayed virtual second and recalculate this simulation scenario.",
  "client.reset_and_run": "Reset and run",
  "client.scheduled_for": " scheduled for ",
  "client.at_virtual": " at virtual ",
  "client.s_the_deterministic_path_was_recalculated": " s. The deterministic path was recalculated.",
  "client.min_3": " /min",
  "client.the_server_request_could_not_be_completed_please_try_again": "The server request could not be completed. Please try again.",
  "client.the_request_failed": "The request failed.",
  "settings.unsaved_changes": "Unsaved changes",
  "settings.discard_unsaved_settings": "Discard unsaved settings?",
  "settings.api_key_saved_for_your_google_account": "API key saved for your Google account.",
  "settings.no_api_key_configured": "No API key configured.",
  "casegallery.switch_to": "Switch to ",
  "casegallery.view": " view",
  "casegallery.no_matching_cases": "No matching cases",
  "casegallery.your_workspace_starts_here": "Your workspace starts here",
  "casegallery.try_a_different_search_or_filter": "Try a different search or filter.",
  "casegallery.create_a_case_to_model_a_line_or_start_with_the_demonstration_case": "Create a case to model a line, or start with the demonstration case.",
  "casegallery.equipment_units": " equipment units",
  "casegallery.public_demo": " · Public demo",
  "casegallery.ready": "Ready",
  "casegallery.draft": "Draft",
  "casegallery.delete": "Delete ",
  "casegallery.previous": "Previous",
  "casegallery.next": "Next",
  "casegallery.page": "Page ",
  "casegallery.of": " of ",
  "results.global_oee": "Global OEE",
  "results.throughput": "Throughput",
  "results.production": "Production",
  "results.equipment_downtime": "Equipment downtime",
  "results.starving": "Starving",
  "results.blocking": "Blocking",
  "results.failure_time": "Failure time",
  "results.complete_a_simulation_to_inspect_the_results": "Complete a simulation to inspect the results.",
  "results.full_run": " · Full run · ",
  "results.s_seed": " s · Seed ",
  "results.primary_kpi": " primary-kpi",
  "results.oee_reference": "OEE reference: ",
  "results.quality_assumes_100_no_reject_model_loss_and_downtime_totals_are_equipment_": ". Quality assumes 100% (no reject model). Loss and downtime totals are equipment-minutes; simultaneous losses are not line downtime.",
  "results.investigate": "Investigate ",
  "results.highest_combined_starving_blocking_and_failure_time_among_machines_this_is_": ": highest combined starving, blocking and failure time among machines. This is a loss indicator, not proof of the line bottleneck.",
  "results.pp": " pp",
  "results.n_a_zero_baseline": "N/A (zero baseline)",
  "shell.open_a_case_first": "Open a case first",
  "shell.workspace": "Workspace",
  "shell.cases": "Cases",
  "shell.line_setup": "Line setup",
  "shell.simulation": "Simulation",
  "shell.results": "Results",
  "shell.what_if": "What-If",
  "shell.save_changes": "Save changes",
  "shell.expand_sidebar": "Expand sidebar",
  "shell.collapse_sidebar": "Collapse sidebar",
  "shell.settings": "Settings",
  "shell.no_matching_commands": "No matching commands.",
  "charts.actual_bpm": "Actual BPM",
  "charts.unit": "Unit ",
  "comparison.select_two_different_simulations": "Select two different simulations.",
  "comparison.scenario_provenance": "Scenario provenance",
  "comparison.simulation_configuration": "Simulation configuration",
  "comparison.simulation_results": "Simulation results",
  "comparison.saved_result_metadata": "Saved result metadata",
  "comparison.equipment": "Equipment · ",
  "comparison.simulation_metrics": "Simulation metrics · ",
  "comparison.added_equipment": "Added equipment",
  "comparison.changed_inputs": "Changed inputs · ",
  "comparison.changes": " changes · ",
  "comparison.equipment_affected": " equipment affected",
  "comparison.no_equipment_input_differences_run_settings_are_listed_below": "No equipment input differences. Run settings are listed below.",
  "comparison.vs": " vs. ",
  "comparison.configuration_can_be_compared_now_run_and_save_both_simulations_before_inte": "Configuration can be compared now. Run both simulations before interpreting result deltas; results are saved automatically.",
  "comparison.paired_run_both_used_seed": "Paired run: both used seed ",
  "comparison.and": " and ",
  "comparison.virtual_seconds_result_differences_can_be_attributed_to_the_saved_configura": " virtual seconds. Matching seed and duration improve comparability but do not guarantee identical failure events or isolate causality when equipment, commands or random-number consumption change.",
  "comparison.comparison_caution_saved_seed_or_virtual_duration_differs": "Comparison caution: saved seed or virtual duration differs (",
  "comparison.s_vs": " s vs. ",
  "comparison.s_configuration_differences_remain_valid_but_rerun_both_with_the_same_seed_": " s). Configuration differences remain valid, but rerun both with the same seed and duration for a direct result comparison.",
  "comparison.no_saved_values": "No saved values.",
  "comparison.comparison_changed": " comparison-changed",
  "assistant.gemini": "Gemini",
  "assistant.saved_case": " · saved case",
  "assistant.gemini_is_analyzing_the_case": "Gemini is analyzing the case…",
  "assistant.add_your_gemini_api_key_in_settings_to_ask_questions": "Add your Gemini API key in Settings to ask questions.",
  "assistant.save_your_changes_before_asking_about_this_case": "Pending edits will be saved before sending your question.",
  "assistant.context_includes_this_saved_case_and_all_saved_simulation_results": "Context uses the selected simulation, aggregate results and physical design checks.",
  "assistant.gemini_could_not_be_reached_try_again": "Gemini could not be reached. Try again.",
  "equipmentdrag.prefers_reduced_motion_reduce": "(prefers-reduced-motion: reduce)",
  "sheetimport.to_add": " to add · ",
  "sheetimport.to_update": " to update · ",
  "sheetimport.metadata_changes": " metadata changes",
  "sheetimport.existing_results_will_be_cleared_run_again": " · Existing results will be cleared; run again.",
  "sheetimport.physical_model_review_drafts_can_be_saved": "Physical model review (drafts can be saved)",
  "sheetimport.import": "Import ",
  "sheetimport.unavailable": "Unavailable",
  "sheetimport.unchanged": "Unchanged",
  "sheetimport.clear_to_na_optional": "Clear to NA (optional)",
  "sheetimport.changed": "Changed",
  "sheetimport.source_equipment": " source equipment · ",
  "sheetimport.choose_what_to_apply_to_this_simulation_existing_equipment_keeps_its_id_and": "Choose what to apply to this simulation. Existing equipment keeps its ID and position; new equipment is appended in Sheet order. Missing Sheet rows never delete equipment. NA fields are not selected by default for existing equipment.",
  "sheetimport.select_differences": "Select differences",
  "sheetimport.deselect_all_fields": "Deselect all fields",
  "sheetimport.case_format_information_select_metadata_to_update": "Case/format information — select metadata to update",
  "sheetimport.row": "Row ",
  "sheetimport.add_equipment": "Add equipment",
  "sheetimport.update": "Update ",
  "sheetimport.import_into": "Import into ",
  "sheetimport.import_target_for_row": "Import target for row ",
  "sheetimport.skip_this_equipment": "Skip this equipment",
  "sheetimport.add_as_new_equipment": "Add as new equipment",
  "sheetimport.update_2": "Update: ",
  "sheetimport.source_errors_affected_fields_are_unavailable": "Source errors — affected fields are unavailable",
  "sheetimport.source_warnings": "Source warnings",
  "sheetimport.mapping_and_model_assumptions": "Mapping and model assumptions",
  "sheetimport.no_response_received_from_apps_script": "No response received from Apps Script.",
  "sheetimport.client_sheet_import_20260917_2_server_version_unavailable_check_that_code_g": "Client sheet-import-20260917-2: server version unavailable. Check that Code.gs and Index.html belong to the same deployment.",
  "sheetimport.apps_script_request_failed": "Apps Script request failed: ",
  "sheetimport.unknown_transport_error": "Unknown transport error",
  "sheetimport.the_simulation_changed_after_preview_preview_again_before_applying": "The simulation changed after preview. Preview again before applying.",
  "sheetimportmerge.type": "Type",
  "sheetimportmerge.name": "Name",
  "sheetimportmerge.critical_machine": "Critical machine",
  "sheetimportmerge.mtbf_min": "MTBF (min)",
  "sheetimportmerge.mttr_min": "MTTR (min)",
  "sheetimportmerge.maximum_speed_bpm": "Maximum speed (bpm)",
  "sheetimportmerge.nominal_running_speed_bpm_initialized_from_f": "Nominal running speed (bpm) — initialized from F",
  "sheetimportmerge.total_length_mm": "Total length (mm)",
  "sheetimportmerge.prime_zone_mm": "Prime zone (mm)",
  "sheetimportmerge.discharge_actual_mm": "Discharge actual (mm)",
  "sheetimportmerge.coding_actual_mm": "Coding actual (mm)",
  "sheetimportmerge.package_length_mm": "Package length (mm)",
  "sheetimportmerge.discharge_pitch_mm": "Discharge pitch (mm)",
  "sheetimportmerge.startup_time_s": "Startup time (s)",
  "sheetimportmerge.bottles_discharged_at_stop": "Bottles discharged at stop",
  "sheetimportmerge.downstream_infeed_pitch_mm": "Downstream infeed pitch (mm)",
  "sheetimportmerge.ramp_up_including_prime_delay_s": "Ramp-up including Prime delay (s)",
  "sheetimportmerge.speed_factor_vs_discharge": "Speed factor vs discharge (%)",
  "sheetimportmerge.coding_speed_factor_vs_previous": "Coding speed factor vs previous (%)",
  "sheetimportmerge.conveyor_factor_vs_previous": "Conveyor factor vs previous (%)",
  "sheetimportmerge.insurance_factor_packages": "Insurance factor (packages)",
  "sheetimportmerge.overspeed_vs_infeed_screw": "Overspeed vs infeed screw (%)",
  "sheetimportmerge.packaging_line": "Packaging line",
  "sheetimportmerge.format_name": "Format name",
  "sheetimportmerge.container_size_oz": "Container size (oz)",
  "sheetimportmerge.bottles_per_case": "Bottles per case",
  "sheetimportmerge.date_of_analysis": "Date of analysis",
  "sheetimportmerge.ambiguous_name_choose_the_equipment_to_update": "Ambiguous name: choose the equipment to update.",
  "sheetimportmerge.name_changed_at_this_source_row_choose_an_existing_equipment_or_add_new": "Name changed at this source row: choose an existing equipment or add new.",
  "sheetimportmerge.new_equipment_appended_to_the_line": "New equipment — appended to the line.",
  "sheetimportmerge.matched_by_a_unique_name_or_previous_import": "Matched by a unique name or previous import.",
  "sheetimportmerge.two_sheet_rows_target_the_same_equipment_skip_one_or_choose_another_target": "Two Sheet rows target the same equipment. Skip one or choose another target.",
  "sheetimportmerge.target_equipment_no_longer_exists_preview_again": "Target equipment no longer exists. Preview again.",
  "sheetimportmerge.fix_this_cell_or_deselect_the_field": ": fix this cell or deselect the field.",
  "sheetimportmerge.mtbf_and_mttr_must_both_be_positive_or_both_na_adjust_the_field_selection": ": MTBF and MTTR must both be positive or both NA. Adjust the field selection.",
  "sheetimportmerge.new_updated_equipment_needs_a_name_and_positive_nominal_speed_select_those_": ": new/updated equipment needs a name and positive nominal speed. Select those fields or skip the row.",
  "sheetimportmerge.fix_or_deselect_the_metadata_field": ": fix or deselect the metadata field.",
  "view.st_line_studio": "ST · Line Studio",
  "view.st": "ST",
  "view.line_studio": "Line Studio",
  "view.a_clearer_view_of_your_line": "A CLEARER VIEW OF YOUR LINE",
  "view.welcome_to_your_workspace": "Welcome to your workspace.",
  "view.explore_your_cases_test_possibilities_and_build_confidence_in_your_next_dec": "Explore your cases, test possibilities and build confidence in your next decision.",
  "view.keep_me_signed_in_on_this_browser": "Keep me signed in on this browser",
  "view.continue_with_google": "Continue with Google",
  "view.uses_the_google_account_authorized_for_this_app": "Uses the Google account authorized for this app.",
  "view.case_navigation": "Case navigation",
  "view.simulations": "Simulations",
  "view.simulations_2": "SIMULATIONS",
  "view.simulations_and_comparison": "Simulations and comparison",
  "view.selected_simulation": "Selected simulation",
  "view.selected_simulation_2": "SELECTED SIMULATION",
  "view.workspace_actions": "Workspace actions",
  "view.close_case": "Close case",
  "view.sign_out": "Sign out",
  "view.sign_out_of_this_workspace": "Sign out of this workspace",
  "view.loading": "Loading",
  "view.your_workspace": "YOUR WORKSPACE",
  "view.your_cases": "Your cases",
  "view.pick_up_where_you_left_off_or_explore_a_new_possibility": "Pick up where you left off, or explore a new possibility.",
  "view.create_demo": "Create demo",
  "view.new_case": "New case",
  "view.new_case_name": "New Case name",
  "view.create_case": "Create case",
  "view.cancel": "Cancel",
  "view.search_your_cases": "Search your cases",
  "view.search_cases": "Search cases…",
  "view.filter_cases": "Filter cases",
  "view.all_cases": "All cases",
  "view.ready_to_simulate": "Ready to simulate",
  "view.drafts": "Drafts",
  "view.sort_cases": "Sort cases",
  "view.recently_updated": "Recently updated",
  "view.name_a_z": "Name A–Z",
  "view.switch_to_grid_view": "Switch to grid view",
  "view.case_editor": "CASE EDITOR",
  "view.case": "Case",
  "view.reload": "Reload",
  "view.clone_simulation": "Clone Simulation",
  "view.delete_case": "Delete Case",
  "view.save_case": "Save Case",
  "view.case_name": "Case name",
  "view.unit_of_flow": "Unit of flow",
  "view.bottles_cases_pallets": "bottles, cases, pallets…",
  "view.equipment_sequence": "Equipment sequence",
  "view.order_defines_material_flow_use_alternating_machine_conveyor_machine_steps_": "Order defines material flow. Use alternating machine → conveyor → machine steps; every conveyor requires physical geometry.",
  "view.import_sheet": "Import Sheet",
  "view.raw_json_preview": "Raw JSON preview",
  "view.run_workspace": "RUN WORKSPACE",
  "view.dynamic_simulation": "Dynamic simulation",
  "view.select_a_saved_case_to_run_it": "Select a saved Case to run it.",
  "view.run_simulation": "Run simulation",
  "view.save_a_valid_physical_line_before_running_machine_conveyor_machine_with_geo": "Configure a valid physical line before running: machine → conveyor → machine, with geometry on every conveyor. Changes save automatically.",
  "view.run_configuration_scheduled_events": "Run configuration & scheduled events",
  "view.duration_mode": "Duration mode",
  "view.fixed_virtual_duration": "Fixed virtual duration",
  "view.indefinite_safety_ceiling": "Indefinite (safety ceiling)",
  "view.virtual_duration_safety_ceiling_s": "Virtual duration / safety ceiling (s)",
  "view.display_sample_interval_s": "Display sample interval (s)",
  "view.random_seed": "Random seed",
  "view.playback_speed_virtual_real": "Playback speed (virtual / real)",
  "view.model_assumptions_timing": "Model assumptions & timing",
  "view.at_1_one_virtual_second_takes_one_real_second_the_engine_integrates_at_0_25": "At 1×, one virtual second takes one real second. The engine integrates at 0.25 s; the display interval only controls replay detail and result size. Every conveyor uses FlowPilot physical geometry by default: L_act, L_p, package pitch, speed factor, runout, sensor delays, and insurance derive capacity, travel, normal photoeye pulses, Prime / Back-up control, recovery, and design audits. Abstract buffers are not used.",
  "view.equipment_control_events": "Equipment control events",
  "view.schedule_a_pause_planned_stop_emergency_stop_reset_run_manual_or_automatic_": "Schedule a pause, planned stop, emergency stop, reset, run, manual, or automatic mode change in virtual time.",
  "view.add_event": "Add event",
  "view.play": "Play",
  "view.virtual_time": "Virtual time",
  "view.output": "Output",
  "view.instantaneous_output_rate": "Instantaneous output rate",
  "view.cumulative_average_rate": "Cumulative average rate",
  "view.accumulation_inventory": "Accumulation inventory",
  "view.overflow_loss": "Overflow loss",
  "view.back_up_control_time": "Back-up control time",
  "view.line_oee_is_final_output_divided_by_the_maximum_output_of_the_selected_pace": "Line OEE is final output divided by the maximum output of the selected pacemaker across the same virtual duration. Quality is assumed 100% until rejects are modeled.",
  "view.scenario_controls_apply_at_the_displayed_virtual_second_and_deterministical": "Scenario controls apply at the displayed virtual second and deterministically recalculate the run. They are simulation controls only; they never command real equipment.",
  "view.performance": "PERFORMANCE",
  "view.run_results": "Run results",
  "view.export_json": "Export JSON",
  "view.no_results_yet": "No results yet",
  "view.run_this_simulation_to_inspect_production_losses_and_equipment_performance": "Run this simulation to inspect production, losses and equipment performance.",
  "view.go_to_simulation": "Go to simulation",
  "view.equipment_comparison": "Equipment comparison",
  "view.cumulative_production": "Cumulative production",
  "view.complete_simulated_duration_output_units": "Complete simulated duration · output units",
  "view.cumulative_output_chart": "Cumulative output chart",
  "view.actual_speed_by_equipment": "Actual speed by equipment",
  "view.full_simulated_duration_series_colors_match_the_live_equipment_trends": "Full simulated duration. Series colors match the live equipment trends.",
  "view.rolling_actual_speed_chart_for_all_equipment": "Rolling actual speed chart for all equipment",
  "view.equipment_speed_chart_legend": "Equipment speed chart legend",
  "view.raw_simulation_result": "Raw simulation result",
  "view.scenario_lab": "SCENARIO LAB",
  "view.review_the_recommendation_for_the_selected_simulation_and_create_a_proposed": "Evaluate the selected simulation and create supported scenarios by investment category.",
  "view.start_with_a_baseline_run": "Start with a baseline run",
  "view.run_the_active_simulation_to_generate_an_evidence_based_recommendation": "Run the active simulation to generate an evidence-based recommendation.",
  "view.simulation_analysis": "SIMULATION ANALYSIS",
  "view.what_this_run_indicates": "What the available evidence indicates",
  "view.the_recommendation_combines_this_run_s_losses_with_the_physical_conveyor_au": "Review zero, medium and high CAPEX options. Evidence labels distinguish static design inputs from dynamic run results. Each action creates a separate simulation.",
  "view.case_comparison": "CASE COMPARISON",
  "view.select_exactly_two_saved_simulations": "Select exactly two saved simulations.",
  "view.baseline": "Baseline",
  "view.proposed_scenario": "Proposed scenario",
  "view.engine_boundary": "Engine boundary",
  "view.the_browser_engine_executes_the_deterministic_case_apps_script_is_responsib": "The browser engine executes the deterministic Case. Apps Script is responsible for identity and Drive persistence; Gemini is not used for calculation. Sensor positions in the public demo are transparent synthetic assumptions, not a PLC or safety-control design.",
  "view.resize_gemini_panel": "Resize Gemini panel",
  "view.drag_to_resize_use_left_and_right_arrows": "Drag to resize; use Left and Right arrows",
  "view.collapse_gemini_panel": "Collapse Gemini panel",
  "view.ask_about_the_saved_case_equipment_and_simulation_results": "Ask about the saved case, equipment and simulation results.",
  "view.case_conversation": "Case conversation",
  "view.question_for_gemini": "Question for Gemini",
  "view.ask_about_this_case": "Ask about this case…",
  "view.clear_case_conversation": "Clear case conversation",
  "view.send": "Send",
  "view.sending_shares_this_saved_case_with_google_gemini_conversations_clear_when_": "Sending shares a compact analysis with Google Gemini. Conversations reset when changing simulation or case.",
  "view.close_settings": "Close settings",
  "view.close_settings_esc": "Close settings (Esc)",
  "view.appearance": "Appearance",
  "view.applied_immediately_on_this_browser": "Applied immediately on this browser.",
  "view.theme": "Theme",
  "view.light": "Light",
  "view.dark": "Dark",
  "view.system_automatic": "System / Automatic",
  "view.accent_color": "Accent color",
  "view.storage_simulation_defaults": "Storage & simulation defaults",
  "view.choose_a_drive_folder_you_can_access_cases_and_results_are_saved_in_this_wo": "Choose a Drive folder you can access. Cases and results are saved in this workspace.",
  "view.drive_folder_id": "Drive folder ID",
  "view.default_playback_speed": "Default playback speed",
  "view.your_api_key_is_stored_in_your_apps_script_user_properties_and_used_only_by": "Your API key is stored in your Apps Script user properties and used only by the server.",
  "view.model_id": "Model ID",
  "view.api_key": "API key",
  "view.leave_blank_to_keep_your_saved_key": "Leave blank to keep your saved key",
  "view.remove_saved_api_key": "Remove saved API key",
  "view.save_settings": "Save settings",
  "view.import_equipment_from_google_sheets": "Import equipment from Google Sheets",
  "view.close_import": "Close import",
  "view.read_c1_c7_and_equipment_rows_a10_w_na_and_n_a_mean_not_applicable_import_u": "Read C1:C7 and equipment rows A10:W. NA and N/A mean not applicable. Compare current and Sheet values, choose equipment and fields, then apply the selected changes. The active simulation saves automatically.",
  "view.google_sheets_url_or_id": "Google Sheets URL or ID",
  "view.https_docs_google_com_spreadsheets_d": "https://docs.google.com/spreadsheets/d/…",
  "view.worksheet_name_optional": "Worksheet name (optional)",
  "view.uses_the_url_tab_or_the_first_worksheet": "Uses the URL tab, or the first worksheet",
  "view.preview_import": "Preview import",
  "view.i_reviewed_the_mapping_assumptions_and_warnings": "I reviewed the mapping, assumptions and warnings.",
  "view.apply_selected_changes": "Apply selected changes",
  "view.command_palette": "Command palette",
  "view.search_commands": "Search commands…",
  "view.search_commands_2": "Search commands",
  "client.this_draft_has_no_equipment_add_at_least_two_units_before_simulation_2": "This draft has no equipment. Add at least two units before simulation.",
  "client.reorder_equipment": "Reorder equipment",
  "client.drag_to_reorder_use_arrow_up_or_down_on_this_handle": "Drag to reorder; use Arrow Up or Down on this handle",
  "client.remove": "Remove",
  "client.equipment_id": "Equipment ID",
  "client.blower": "Blower",
  "client.blowmolder": "Blowmolder",
  "client.conveyor": "Conveyor",
  "client.pacemaker": "Pacemaker",
  "client.pucker": "Pucker",
  "client.filler": "Filler",
  "client.de_pucker": "De-pucker",
  "client.sleever": "Sleever",
  "client.case_packer": "Case packer",
  "client.palletizer": "Palletizer",
  "client.other_custom": "Other / custom",
  "client.nominal_rate_sec": "Nominal rate / sec",
  "client.initial_mode": "Initial mode",
  "client.automatic": "Automatic",
  "client.manual": "Manual",
  "client.paused": "Paused",
  "client.stopped": "Stopped",
  "client.flowpilot_conveyor_design": "FlowPilot conveyor design",
  "client.required_for_every_conveyor_geometry_is_always_active_the_engine_derives_co": "Required for every conveyor. Geometry is always active: the engine derives conveyor velocity, pitch, capacity, Prime, Back-up margin, recovery, and audit from these named inputs.",
  "client.installed_length_l_act_mm": "Installed length L_act (mm)",
  "client.prime_reserve_l_p_mm": "Prime reserve L_p (mm)",
  "client.upstream_discharge_pitch_mm": "Upstream discharge pitch (mm)",
  "client.conveyor_speed_factor": "Conveyor speed factor (%)",
  "client.installed_back_up_position_mm": "Installed Back-up position (mm)",
  "client.discharge_runout_mm": "Discharge runout (mm)",
  "client.reject_runout_mm": "Reject runout (mm)",
  "client.blocked_time_delay_s": "Blocked time delay (s)",
  "client.clear_time_delay_s": "Clear time delay (s)",
  "client.insurance_factor_units": "Insurance factor (units)",
  "client.upstream_stop_response_s": "Upstream stop response (s)",
  "client.downstream_ramp_up_s": "Downstream ramp-up (s)",
  "client.advanced_json_fields": "Advanced JSON fields",
  "client.characteristics_json_optional": "Characteristics JSON (optional)",
  "client.noise_profile_json_optional": "Noise profile JSON (optional)",
  "client.advanced_process_format_json_optional": "Advanced process format JSON (optional)",
  "client.compare_2": "Compare",
  "client.no_scheduled_control_events_2": "No scheduled control events.",
  "client.at_virtual_second": "At virtual second",
  "client.equipment": "Equipment",
  "client.action": "Action",
  "client.run": "Run",
  "client.reset_emergency_stop": "Reset emergency stop",
  "client.state_rate": "State & rate",
  "client.units_oee": "Units & OEE",
  "client.speed_trend": "Speed trend",
  "client.scenario_controls": "Scenario controls",
  "client.oee_availability_performance_quality_quality_is_assumed_100_until_the_model": "OEE = Availability × Performance × Quality. Quality is assumed 100% until the model includes rejected units.",
  "client.oee": "OEE",
  "client.starved": "Starved",
  "client.blocked_2": "Blocked",
  "client.waiting_prime": "Waiting Prime",
  "client.back_up_stop": "Back-up stop",
  "client.failure_2": "Failure",
  "client.emergency": "Emergency",
  "client.actual_last_60_s": "Actual · last 60 s",
  "client.rolling_actual_speed_chart": "Rolling actual-speed chart",
  "client.inventory": "Inventory",
  "client.in_transit": "In transit",
  "client.prime": "Prime",
  "client.back_up": "Back-up",
  "client.geometry": "Geometry",
  "client.travel": "Travel",
  "client.overflow": "Overflow",
  "client.conveyor_design_audit": "Conveyor design audit",
  "client.required_overflow_l_bu": "Required overflow L_bu",
  "client.useful_accumulation_l_ba": "Useful accumulation L_ba",
  "client.recovery_l_rec": "Recovery L_rec",
  "client.anti_starve": "Anti-starve",
  "client.anti_block": "Anti-block",
  "client.recommended_speed": "Recommended speed",
  "results.produced_processed": "Produced / processed",
  "results.starved_min": "Starved · min",
  "results.blocked_min": "Blocked · min",
  "results.failure_min": "Failure · min",
  "results.failures": "Failures",
  "results.outcome_comparison": "Outcome comparison",
  "results.metric": "Metric",
  "results.proposed": "Proposed",
  "results.absolute": "Absolute Δ",
  "results.relative": "Relative Δ"
};

function __ST_TEXT__(key) {
  if (!Object.prototype.hasOwnProperty.call(ST_TEXT_RESOURCES, key)) throw new Error('Unknown text resource: ' + key);
  return ST_TEXT_RESOURCES[key];
}

function resolveTextResources_(source) {
  function html(value) {
    return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }
  return source.replace(/<\?=\s*__ST_TEXT__\('([^']+)'\)\s*\?>/g, function(_, key) {
    return html(__ST_TEXT__(key));
  }).replace(/(__ST_TEXT__|__ST_HTML_TEXT__)\('([^']+)'\)/g, function(_, kind, key) {
    var value = __ST_TEXT__(key);
    if (kind === '__ST_HTML_TEXT__') value = html(value);
    return JSON.stringify(value).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
  });
}
